# Generated by Django 5.2.10 on 2026-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_avatar_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
